type ChartWeek={id:string;label:string;metrics:Record<string,number>};
export function initAnalyticsReport(){
 const root=document.querySelector<HTMLElement>("[data-analytics-report]"); if(!root||root.dataset.ready)return; root.dataset.ready="true";
 const tabs=[...root.querySelectorAll<HTMLButtonElement>("[data-report-tab]")],panels=[...root.querySelectorAll<HTMLElement>("[data-report-panel]")];
 const activate=(id:string,focus=false)=>{if(!panels.some(p=>p.id===id))id="overview";tabs.forEach(t=>{const on=t.dataset.reportTab===id;t.setAttribute("aria-selected",String(on));t.tabIndex=on?0:-1});panels.forEach(p=>p.hidden=p.id!==id);history.replaceState(null,"",`#${id}`);if(focus)document.getElementById(id)?.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion:reduce)").matches?"auto":"smooth",block:"start"})};
 tabs.forEach((tab,i)=>{tab.addEventListener("click",()=>activate(tab.dataset.reportTab!,true));tab.addEventListener("keydown",e=>{if(e.key==="ArrowRight"||e.key==="ArrowLeft"){e.preventDefault();tabs[(i+(e.key==="ArrowRight"?1:-1)+tabs.length)%tabs.length].click()}})});root.querySelectorAll("[data-back-overview]").forEach(b=>b.addEventListener("click",()=>activate("overview",true)));activate(location.hash.slice(1)||"overview");addEventListener("hashchange",()=>activate(location.hash.slice(1)||"overview"));root.querySelector("[data-print]")?.addEventListener("click",()=>print());
 const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;const el=entry.target as HTMLElement,target=Number(el.dataset.counter),start=performance.now();const tick=(now:number)=>{const p=Math.min(1,(now-start)/1100);el.textContent=Math.round(target*(1-Math.pow(1-p,3))).toLocaleString("en-IN");if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);observer.unobserve(el)}),{threshold:.4});root.querySelectorAll<HTMLElement>("[data-counter]").forEach(el=>observer.observe(el));
 root.querySelectorAll("[data-metric-card]").forEach(card=>card.addEventListener("click",()=>card.classList.toggle("is-active")));
 const chart=root.querySelector<HTMLElement>("[data-chart]");if(chart){const weeks=JSON.parse(chart.dataset.weeks!) as ChartWeek[],bars=chart.querySelector<SVGGElement>("[data-chart-bars]")!,tooltip=chart.querySelector<HTMLElement>("[data-chart-tooltip]")!;const draw=(metric:string,label:string)=>{const max=Math.max(...weeks.map(w=>w.metrics[metric]));bars.innerHTML="";weeks.forEach((w,i)=>{const h=w.metrics[metric]/max*220,x=105+i*155,y=275-h;const g=document.createElementNS("http://www.w3.org/2000/svg","g");g.innerHTML=`<rect x="${x}" y="${y}" width="76" height="${h}" rx="10" fill="url(#none)" style="fill:${i===0?'#c6a972':'#6d2633'}" tabindex="0" role="button" aria-label="${w.label}: ${w.metrics[metric].toLocaleString('en-IN')} ${label}"/><text x="${x+38}" y="305" text-anchor="middle" fill="#ddd0c6" font-size="13">${w.label}</text>`;const show=(e:Event)=>{const r=(e.currentTarget as Element).getBoundingClientRect(),c=chart.getBoundingClientRect();tooltip.textContent=`${w.label} · ${w.metrics[metric].toLocaleString('en-IN')} ${label}`;tooltip.hidden=false;tooltip.style.left=`${r.left-c.left}px`;tooltip.style.top=`${Math.max(0,r.top-c.top-48)}px`};g.querySelector("rect")!.addEventListener("pointerenter",show);g.querySelector("rect")!.addEventListener("focus",show);g.querySelector("rect")!.addEventListener("pointerleave",()=>tooltip.hidden=true);bars.append(g)});chart.querySelector("title")!.textContent=`Weekly ${label} comparison`};root.querySelectorAll<HTMLButtonElement>("[data-chart-metric]").forEach(b=>b.addEventListener("click",()=>{root.querySelectorAll("[data-chart-metric]").forEach(x=>x.classList.remove("active"));b.classList.add("active");draw(b.dataset.chartMetric!,b.textContent!)}));draw("views","Views")}
}
